# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/dell/streak7/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
vendor/dell/streak7/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
vendor/dell/streak7/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
vendor/dell/streak7/proprietary/lib/libaudiopolicy.so:obj/lib/libaudiopolicy.so \
vendor/dell/streak7/proprietary/lib/libril.so:obj/lib/libril.so

PRODUCT_COPY_FILES += \
 vendor/dell/streak7/proprietary/vendor/firmware/fw_bcm4329.bin:system/vendor/firmware/fw_bcm4329.bin \
 vendor/dell/streak7/proprietary/vendor/firmware/fw_bcm4329_apsta.bin:system/vendor/firmware/fw_bcm4329_apsta.bin \
 vendor/dell/streak7/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
 vendor/dell/streak7/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
 vendor/dell/streak7/proprietary/lib/hw/audio.primary.tegra.so:system/lib/hw/audio.primary.tegra.so \
 vendor/dell/streak7/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
 vendor/dell/streak7/proprietary/usr/keylayout/tegra_keypad.kl:system/usr/keylayout/tegra_keypad.kl \
 vendor/dell/streak7/proprietary/lib/modules/dhd.ko:system/lib/modules/dhd.ko \
 vendor/dell/streak7/proprietary/lib/hw/dhd.ko:system/lib/hw/dhd.ko \
 vendor/dell/streak7/proprietary/lib/libaudio.so:system/lib/libaudio.so \
 vendor/dell/streak7/proprietary/bin/wifid:system/bin/wifid \
 vendor/dell/streak7/proprietary/bin/lfinit:system/bin/lfinit \
 vendor/dell/streak7/proprietary/bin/lftool:system/bin/lftool \
 vendor/dell/streak7/proprietary/lib/hw/lights.p3.so:system/lib/hw/lights.p3.so \
 vendor/dell/streak7/proprietary/lib/hw/sensors.p3.so:system/lib/hw/sensors.p3.so \
 vendor/dell/streak7/proprietary/bin/rild:system/bin/rild \
 vendor/dell/streak7/proprietary/bin/sdcard:system/bin/sdcard \
 vendor/dell/streak7/proprietary/bin/sensors_daemon:system/bin/sensors_daemon \
 vendor/dell/streak7/proprietary/bin/glgps_nvidiaTegra2android:system/bin/glgps_nvidiaTegra2android \
 vendor/dell/streak7/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
 vendor/dell/streak7/proprietary/lib/libmllite.so:system/lib/libmllite.so \
 vendor/dell/streak7/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
 vendor/dell/streak7/proprietary/lib/libmpl.so:system/lib/libmpl.so \
 vendor/dell/streak7/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
 vendor/dell/streak7/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
 vendor/dell/streak7/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
 vendor/dell/streak7/proprietary/lib/libnvcontrol_jni.so:system/lib/libnvcontrol_jni.so \
 vendor/dell/streak7/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
 vendor/dell/streak7/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
 vendor/dell/streak7/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
 vendor/dell/streak7/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
 vendor/dell/streak7/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
 vendor/dell/streak7/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
 vendor/dell/streak7/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
 vendor/dell/streak7/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
 vendor/dell/streak7/proprietary/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
 vendor/dell/streak7/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
 vendor/dell/streak7/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
 vendor/dell/streak7/proprietary/lib/omxplayer.so:system/lib/omxplayer.so \
 vendor/dell/streak7/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
 vendor/dell/streak7/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
 vendor/dell/streak7/proprietary/lib/liba2dp.so:system/lib/liba2dp.so \
 vendor/dell/streak7/proprietary/lib/libasound.so:system/lib/libasound.so \
 vendor/dell/streak7/proprietary/lib/libaudio.so:system/lib/libaudio.so \
 vendor/dell/streak7/proprietary/lib/libaudiopolicy.so:system/lib/libaudiopolicy.so \
 vendor/dell/streak7/proprietary/lib/libcamera.so:system/lib/libcamera.so \
 vendor/dell/streak7/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
 vendor/dell/streak7/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
 vendor/dell/streak7/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
 vendor/dell/streak7/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
 vendor/dell/streak7/proprietary/lib/libnvddk_aes_user.so:system/lib/libnvddk_aes_user.so \
 vendor/dell/streak7/proprietary/lib/libnvddk_audiofx.so:system/lib/libnvddk_audiofx.so \
 vendor/dell/streak7/proprietary/lib/libnvddk_vmr.so:system/lib/libnvddk_vmr.so \
 vendor/dell/streak7/proprietary/lib/libnvdispatch_helper.so:system/lib/libnvdispatch_helper.so \
 vendor/dell/streak7/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
 vendor/dell/streak7/proprietary/lib/libnvec.so:system/lib/libnvec.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_tracklist.so:system/lib/libnvmm_tracklist.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_videorenderer.so:system/lib/libnvmm_videorenderer.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
 vendor/dell/streak7/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
 vendor/dell/streak7/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
 vendor/dell/streak7/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
 vendor/dell/streak7/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
 vendor/dell/streak7/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
 vendor/dell/streak7/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
 vendor/dell/streak7/proprietary/lib/libnvos.so:system/lib/libnvos.so \
 vendor/dell/streak7/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
 vendor/dell/streak7/proprietary/lib/libnvrm_channel.so:system/lib/libnvrm_channel.so \
 vendor/dell/streak7/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
 vendor/dell/streak7/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
 vendor/dell/streak7/proprietary/lib/libnvtestio.so:system/lib/libnvtestio.so \
 vendor/dell/streak7/proprietary/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
 vendor/dell/streak7/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
 vendor/dell/streak7/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
 vendor/dell/streak7/proprietary/etc/firmware/nvddk_audiofx_core.axf:system/etc/firmware/nvddk_audiofx_core.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvddk_audiofx_transport.axf:system/etc/firmware/nvddk_audiofx_transport.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_audiomixer.axf:system/etc/firmware/nvmm_audiomixer.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_mp2dec.axf:system/etc/firmware/nvmm_mp2dec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_sorensondec.axf:system/etc/firmware/nvmm_sorensondec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
 vendor/dell/streak7/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
 vendor/dell/streak7/proprietary/etc/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
 vendor/dell/streak7/proprietary/etc/nvram.txt:system/etc/nvram.txt \
 vendor/dell/streak7/proprietary/etc/asound.conf:system/etc/asound.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/rear.conf:system/usr/share/alsa/pcm/rear.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/surround71.conf:system/usr/share/alsa/pcm/surround71.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/surround40.conf:system/usr/share/alsa/pcm/surround40.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/iec958.conf:system/usr/share/alsa/pcm/iec958.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/side.conf:system/usr/share/alsa/pcm/side.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/modem.conf:system/usr/share/alsa/pcm/modem.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/center_lfe.conf:system/usr/share/alsa/pcm/center_lfe.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/surround50.conf:system/usr/share/alsa/pcm/surround50.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/surround51.conf:system/usr/share/alsa/pcm/surround51.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/surround41.conf:system/usr/share/alsa/pcm/surround41.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/front.conf:system/usr/share/alsa/pcm/front.conf \
 vendor/dell/streak7/proprietary/usr/share/alsa/pcm/dpl.conf:system/usr/share/alsa/pcm/dpl.conf \
 vendor/dell/streak7/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
 vendor/dell/streak7/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
 vendor/dell/streak7/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
 vendor/dell/streak7/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
 vendor/dell/streak7/proprietary/lib/gps.tegra.so:system/lib/gps.tegra.so \
 vendor/dell/streak7/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
 vendor/dell/streak7/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
 vendor/dell/streak7/proprietary/lib/hw/overlay.tegra.so:system/lib/hw/overlay.tegra.so \
 vendor/dell/streak7/proprietary/lib/hw/tegra_alsa.streak7.so:system/lib/hw/tegra_alsa.streak7.so \
 vendor/dell/streak7/proprietary/lib/gps.tegra.so:system/lib/gps.tegra.so \
 vendor/dell/streak7/proprietary/bin/nv_hciattach:system/bin/nv_hciattach \
 vendor/dell/streak7/proprietary/bin/nvrm_daemon:system/bin/nvrm_daemon \
 vendor/dell/streak7/proprietary/bin/nvtest:system/bin/nvtest \
 vendor/dell/streak7/proprietary/bin/glgps:system/bin/glgps \
 vendor/dell/streak7/proprietary/etc/gps.conf:system/etc/gps.conf \
 vendor/dell/streak7/proprietary/etc/gpsconfig.xml:system/etc/gpsconfig.xml \
 vendor/dell/streak7/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
 vendor/dell/streak7/proprietary/lib/libhuawei-ril.so:system/lib/libhuawei-ril.so \
 vendor/dell/streak7/proprietary/lib/libril.so:system/lib/libril.so
